# -- mode: ruby --
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 if Vagrant.has_plugin? "vagrant-vbguest"
 config.vbguest.no_install = true
 config.vbguest.auto_update = false
 config.vbguest.no_remote = true
 end
 config.vm.define :cliente do |cliente|
 config.vm.box = "diegomaya_perea/Copia_cliente"
 config.vm.box_version = "0.0.1"
 cliente.vm.network :private_network, ip: "192.168.50.2"
 cliente.vm.hostname = "cliente"
 cliente.vm.synced_folder ".","/vagrant"
 end
 config.vm.define :servidor do |servidor|
 config.vm.box = "diegomaya_perea/Copia_servidor"
 config.vm.box_version = "0.0.1"
 servidor.vm.network :private_network, ip: "172.16.0.3"
 servidor.vm.network :private_network, ip: "192.168.50.3"
 servidor.vm.hostname = "servidor"
 servidor.vm.synced_folder ".","/vagrant"
 end
end