Vagrant.configure("2") do |config|
 if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
end
config.vm.define :firewall do |firewall|
  config.vm.box = "simoncolmenares/servidor"
  config.vm.box_version = "0.0.1"
  firewall.vm.network :private_network, ip: "172.16.0.3"
  firewall.vm.network :private_network, ip: "192.168.50.3"
  firewall.vm.hostname = "firewall"
  end
config.vm.define :maestro do |maestro|
  config.vm.box = "simoncolmenares/servidor"
  config.vm.box_version = "0.0.1"
  maestro.vm.network :private_network, ip: "192.168.50.4"
  maestro.vm.hostname = "maestro"
  end

 config.vm.define :esclavo do |esclavo|
  config.vm.box = "simoncolmenares/servidor"
  config.vm.box_version = "0.0.1"   
  esclavo.vm.network :private_network, ip: "192.168.50.2"
  esclavo.vm.hostname = "esclavo"
  end
end
